prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE

one-day-hero/src/components/common/Day/DayButton.tsx, one-day-hero/src/components/common/Day/DayList.tsx, one-day-hero/src/components/common/Label.tsx
요일 버튼과 요일 전체 컴포넌트 생성했습니다. 
나머지 로직은 api가 연결되면 수정 할 것 같습니다. 
`<DayList/>` 넣어서 사용하시면 됩니다. 
https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/0adaa8d2-af3f-473d-a544-ccac647019cc
더 좋은 방법이 있는 지 궁금합니다. 
- closes #
=> 요일 버튼과 요일 전체 컴포넌트

one-day-hero/src/app/api/v1/mock/missions/create/route.ts, one-day-hero/src/app/mission/create/page.tsx
- 미션 생성에 관한 POST 요청을 보낸 후 명세서에 맞는 응답을 내려주도록 테스트 해보았습니다.
위 스크린샷은 응답을 받아와서 잘 사용할 수 있는지 테스트 한 부분입니다.
- 일단은 주어진 정보가 적어서 더미를 받아오는 것처럼 구현했는데 잘 한건지 모르겠네요..
- type과 dummy로 보내는 요청은 생성 페이지 양식에 맞게 삭제 후 진행할 예정입니다.
- closes #80
=> 미션 생성 Mock 데이터 테스트

one-day-hero/src/components/common/UploadImage.tsx
이미지 업로드 컴포넌트를 구현합니다.
- 기본 default 사이즈는 md 사이즈로 미션 이미지 업로드 용이며 최대 3개까지 선택 가능합니다.
- `<UploadImage size='lg' />` 로 쓰시면 1개만 업로드 가능한 프로필 용 업로드 컴포넌트가 됩니다.
- delete 부분은 비교할 부분이 아직 애매해서 추후 구현 예정입니다.
- md 사이즈
https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/117630589/8d24626c-0323-4286-a54f-7dbc21dab91c
- lg 사이즈
https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/117630589/48fab751-e397-4a08-b7df-95d64395fb43
- closes #82
=> 이미지 업로드 컴포넌트 구현

one-day-hero/src/app/citizenProfile/[slug]/page.tsx, one-day-hero/src/app/error.tsx, one-day-hero/src/app/heroProfile/[slug]/page.tsx, one-day-hero/src/app/mission/[slug]/page.tsx, one-day-hero/src/app/mission/list/ongoing/page.tsx, one-day-hero/src/app/mission/list/suggested/page.tsx, one-day-hero/src/app/mission/record/page.tsx, one-day-hero/src/app/page.tsx, one-day-hero/src/components/common/BookmarkButton.tsx, one-day-hero/src/components/domain/mission/create/CreateForm.tsx, one-day-hero/src/components/domain/missionDetail/CitizenInfo.tsx, one-day-hero/src/services/base.ts, one-day-hero/src/services/missions.ts, one-day-hero/src/services/urls.ts, one-day-hero/src/services/users.ts, one-day-hero/src/types/response.ts
- SSR 환경에서 fetch 함수의 에러처리가 ErrorBoundary로 해결할 수 없어서 자체적으로 에러처리 기능을 추가했습니다.
- `useFetch` 라는 이름으로 추상화했습니다. tanstack query의 `useQuery`를 따라했습니다.
- fetch에 인자로 넣을 `pathname`과 `options`를 전달해 사용합니다.
- fetch 완료 실행될 `callback`을 전달할 수 있습니다. revalidation에 사용하면 괜찮을 것 같아서 추가했습니다.
- fetch함수의 반환 값이 기존에는 응답 데이터였지만 지금은 `isError`라는 에러 여부 값과 `response` 값을 반환합니다.
- `isError` 가 true 일 땐 `ErrorPage`를 서버에서 렌더링하도록 페이지들을 수정했습니다.
- typescript의 추론을 위해 `isError` 조건에 `!response` 조건도 같이 검사합니다.
- POST, DELETE 등은 hook 규칙에 벗어나 조건문이나 handler 안에서 쓰여야할 경우가 많아서 `useMutationalFetch`로 분리했습니다.
- tanstack query의 `useMutaion` 컨셉을 따왔습니다.
- useFetch를 bind해서 조건부로 사용할 수 있도록 했습니다.
- 에러 페이지
>
일단 간단히 만들었습니다.
- 에러 페이지에서 `revalidatePath`를 쓰고 싶었는데 `Error: Invariant: static generation store missing in revalidateTag _N_T_{pathname}` 라는 알 수 없는 …
=> Data Fetching 함수 에러 처리 추상화

one-day-hero/package-lock.json, one-day-hero/package.json, one-day-hero/src/components/common/UploadImage.tsx, one-day-hero/src/components/domain/mission/create/CreateForm.tsx, one-day-hero/src/components/domain/review/ReviewForm.tsx, one-day-hero/src/components/domain/survey/MandatorySurvey.tsx, one-day-hero/src/types/index.ts
- 이미지 업로드 컴포넌트 이미지 파일에 고유한 아이디를 생성하여 업로드 후에도 지울 수 있도록 구현하였습니다.
- 각 페이지들에서는 타입 부분만 id를 추가한 타입으로 변경했습니다.
UploadImage 컴포넌트 조건문을 간결하게 써보려고 했는데 size가 md 일 때만 3개 이상인지 검사하는 조건이 들어가고 lg 사이즈면 multiple이 아닌 단일 파일 선택이라 그 자체를 상태값으로 넣어주고 있는데 제가 부족해서 그런지 잘 안되네요.. 좋은 방법이 있다면 알려주세요!!
- closes #132
=> 이미지 업로드 컴포넌트 삭제 기능 추가

one-day-hero/src/components/common/Category.tsx
카테고리를 미선택 시 에러메세지가 가로스크롤에 부착되어 버리는 버그를 수정했습니다.
가로 스크롤 자체에 `cs:flex-col` 을 줘서 해결하는 방법도 있었지만 가로 스크롤은 가로 스크롤 용도로만 사용하는게 좋겠다 하는 생각에 상단에 div를 생성하여 감싸줬습니다.
- closes #134
=> 카테고리 미선택 시 에러메세지 버그 수정

one-day-hero/src/app/review/[slug]/edit/layout.tsx, one-day-hero/src/app/review/[slug]/edit/page.tsx, one-day-hero/src/components/domain/review/ReviewForm.tsx
- UI가 생성 페이지와 다른 부분이 없어서 별다른 수정 없이 구현했습니다!!
- editMode 면 수정 페이지의 버튼과 editMode가 아니면 생성 페이지의 버튼과 폼을 연결했습니다.
- 
url 구조는 일단 review라는 폴더를 따로 만들고 `review/[reviewId] -> 상세페이지 review/[reviewId]/edit 수정 페이지` 식으로 구현하려고 하는데 괜찮을까요?? 상세페이지 컴포넌트를 만들면서 수정 버튼을 클릭하면 데이터를 넘겨 edit에서는 그 아이디를 가진 리뷰의 정보를 미리 가지고 있는 식으로 구현하려고 합니다! 
- closes #136
=> 리뷰 수정 페이지 UI 구현

one-day-hero/src/app/api/v1/mock/_data/user/index.ts, one-day-hero/src/app/api/v1/mock/me/route.ts, one-day-hero/src/components/domain/survey/MandatorySurvey.tsx, one-day-hero/src/services/base.ts, one-day-hero/src/services/users.ts, one-day-hero/src/types/index.ts, one-day-hero/src/types/request.ts, one-day-hero/src/types/response.ts
- 유저 정보 수정 mock api를 만들었습니다.
- 요청과 응답의 타입이 달라 따로 types에 저장했습니다.
- body에 넣어주는 값을 체크할 수 있도록 route handler에 zod를 사용했습니다.
- `useMutationalFetch`의 로직을 수정했습니다.
- 기존에는 선언할 때 fetch options나 callback 등의 인수를 넣고 사용하는 방식이었습니다.
- 현재는 선언 때 받아온 `mutationalFetch`를 사용할 때 인수를 넣도록 수정했습니다.
- submit handler에서 사용할 때 fetch options로 body를 넣어주면 됩니다.
- 기존 callback이라고 이름 지어둔 인수는 onSuccess와 onError로 바꿨습니다.
- 수정한 로직을 `/survey/mandatory` 페이지에서 시험삼아 적용해봤습니다.
- > 진경님이 작업 중인걸 미처 생각 못하고 REST 문서 맨 위 부터 작업해서 겹쳤습니다. 나중에 해당 페이지 구현 작업 머지되면 제가 충돌 처리해서 PR 수정하겠습니다.
- 테스트 결과 지금 작동은 합니다.
- onSuccess 에 revalidateTag 를 실행 시키려고 했더니 ISR어쩌구 하는 오류가 나더라고요. 왠지 느낌 상 클라이언트 컴포넌트에서 revalidation 쓰려면 route handler를 거쳐서 서버에서 revalidation을 실행 시켜야할 것 같네요.
- closes #143
=> useMutationalFetch 로직 수정 및 유저 정보 수정 Mock api 작성

one-day-hero/src/app/api/v1/mock/_data/mission/index.ts, one-day-hero/src/app/api/v1/mock/_data/user/index.ts, one-day-hero/src/app/api/v1/mock/me/route.ts, one-day-hero/src/app/api/v1/mock/missions/progress/[slug]/route.ts, one-day-hero/src/app/mission/list/ongoing/page.tsx, one-day-hero/src/components/domain/survey/MandatorySurvey.tsx, one-day-hero/src/services/base.ts, one-day-hero/src/services/missions.ts, one-day-hero/src/services/users.ts, one-day-hero/src/types/index.ts, one-day-hero/src/types/request.ts, one-day-hero/src/types/response.ts
- pagenation 방식으로 응답이 내려오는 API 용 fetch 함수인 `useInfiniteFetch` 를 구현했습니다.
- 첫 데이터가 오는 것만 확인했는데 다음 값이 data에 추가돼서 반영될 지는 실제 api에서 테스트해봐야 할 것 같습니다.
- 반환 메서드의 이름은 tanstack query를 참고했습니다.
- 현재 응답 값의 필드 이름(`missionProgressResponses` 등)이 제각각인데 `response`로 통합한다는 가정하에 작성했습니다.
- 진행중인 미션 페이지에 반영해서 테스트 해보았습니다.
- 무한스크롤을 intersection observer로 구현할지.. 일단 더보기 버튼만 대충 넣을지.. 고민이 되네요
- closes #145
=> pagenation api 용 usefetch 구현 및 진행중 미션 mock 데이터 업데이트

one-day-hero/src/app/layout.tsx, one-day-hero/src/components/common/Toast.tsx, one-day-hero/src/components/common/UploadImage.tsx, one-day-hero/src/contexts/ToastProvider.tsx, one-day-hero/tailwind.config.ts
공용으로 사용될 Toast UI를 구현했습니다.
사용할 부분에서 `const { showToast } = useToast()` 로 불러와준 후 showToast 에 매개변수로 첫 번째는 에러메세지, 두 번째는
warn, error, success 셋 중 하나의 타입을 설정해 주시면 됩니다!
`showToast('이건 테스트입니다', 'warn')`
https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/117630589/adf9e3b3-5ca4-4b6f-b473-3761390b0048
`context`를 이용하는 방법과 react portal을 이용하는 방법이 있었는데 사용하는 컴포넌트 단에서 context api를 사용하면 좀 더 간단하게 사용할 수 있을 것 같아서 context로 구현했는데 괜찮을까요??
루트 레이아웃 진경님이 구현해주신 Provider 상단에 Toast Provider를 배치했는데 위치가 괜찮을 지 모르겠네요..
일단은 1개만 사용되도록 구현했는데 배열로 만들면 여러 개를 띄울수도 있을 것 같더라구요..
- closes #147
=> 공용 toast 컴포넌트 구현

one-day-hero/src/components/domain/mission/create/CreateForm.tsx, one-day-hero/src/components/domain/mission/create/CustomCalendar.tsx, one-day-hero/src/hooks/useFormValidation.ts
미션 생성 폼 가격 부분에서 string 타입으로 되어있던걸 number로 바꾸고 날짜 형식을 백엔드 api 명세서와 맞췄습니다.
미션 시작, 끝에 관한 시간도 H:MM 으로 되어있던 부분이 있었는데 전부 HH:MM 으로 통일시켰습니다.
- closes #149
=> 미션 생성 폼 데이터 수정

one-day-hero/package-lock.json, one-day-hero/src/app/api/v1/mock/_data/survey/index.ts, one-day-hero/src/app/survey/category/page.tsx, one-day-hero/src/components/common/DayList.tsx, one-day-hero/src/components/common/Select.tsx, one-day-hero/src/components/common/ToggleButton.tsx, one-day-hero/src/components/domain/survey/MandatorySurvey.tsx, one-day-hero/src/components/domain/survey/OptionalSurvey.tsx, one-day-hero/src/types/response.ts, one-day-hero/src/types/schema.ts
프로필 조사 폼 선택 클라이언트 단 내부 로직 구현했습니다. 
> 자잘하게 올라가 있는 파일들이 많은데 OptionalSurvey 컴포넌트만 봐주시면 됩니다. 
react-hook-form 과 zod를 이용해서 type과 스키마를 지정해주고 select 항목마다 검사할 수 있게 구현했습니다. 
선택한 선호지역을 삭제하는 기능에 관해서 고민을 많이 해봤는데, UI측면에서 클릭한 선호지역 라벨을 삭제하는 건 가능하나, 서버에 보낼 선호지역 id 배열 값에서 또한 삭제하려면 클릭하는 라벨 부분에서도 id 값을 뽑아올 수 있어야 합니다. 그러면  id와 구+동 값을 담고있는 객체 배열 구조로 구조를 바꿔야 할 것 같아 조금 진행해 봤는데 로직이 너무 복잡해 지는 것 같았습니다. 
그래서 대안으로 가장 마지막에 들어온 선호지역 id값에 대해서 삭제를 하는 쪽으로 구현해봤는데 괜찮을까요?? 
혹시 아이디어가 있으시면 공유해주세요!
이미 선택한 선호지역일 경우 와 선호지역이 5개가 넘어가게 되는 경우 우선 alert가 뜨게 했는데 추후 toast로 바꾸겠습니다. 
https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/4fba9f7c-4ef9-44c5-a3af-eaa25fd79d37
수평스크롤 컴포넌트가 마우스로 click drag 가 안되는데 혹시 따로 부여해야 하는 속성이 있을까요??
- closes #
=> 프로필 조사 폼선택 클라이언트 단 내부 로직

one-day-hero/src/app/api/v1/mock/_data/user/index.ts, one-day-hero/src/app/citizenProfile/[slug]/page.tsx, one-day-hero/src/app/heroProfile/[slug]/page.tsx, one-day-hero/src/app/profile/page.tsx, one-day-hero/src/types/response.ts
- 본인 프로필, 히어로 프로필, 시민 프로필 의 데이터를 업데이트합니다.
- UserResponse의 일부 타입은 null로 올 수 있어서 변경했습니다. 
- closes #179
=> 프로필 페이지들 데이터 업데이트

one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
선택 조사 페이지에서 5개 이상 지역을 선택하거나, 중복된 지역을 선택했을 경우 토스트를 띄우게 했습니다. 
https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/40d85bcc-c974-4cc6-be8d-8b735f708de2
가로스크롤이 스마트폰 크기에서 안 먹히네요.
- closes #206
=> 선택 조사 페이지 토스트 적용

one-day-hero/src/app/search/mission/page.tsx, one-day-hero/src/components/common/Category.tsx, one-day-hero/src/components/common/Info/MissionListItem.tsx, one-day-hero/src/components/common/Label.tsx
- 홈페이지에 카테고리를 선택했을 경우 검색페이지에 카테고리 클릭이 반영되지 않았던 문제를 해결했습니다. 
- 지역 정보를 한번 선택한 경우에 구와 동 정보가 필터에 고정 되어 있는데, 새롭게 구 를 선택하게 되어도 이전에 선택한 동의 텍스트가 남아있는 문제가 있었는데 해결했습니다. 
- 서버에서 받아오는 카테고리가 `배달·운전` 이 아닌 `배달,운전` 으로 오는 것 같더라구요. (개인적으로 첫번째꺼 처럼 왔으면 좋겠는데.. ) 그래서 텍스트가 밖으로 나가는 문제 해결했습니다. 
https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/868f9886-2b51-43a4-aade-4ac18c82969a
여기 수평 스크롤은 무조건 되야 하는데... 안 되네요.. 그때 fixed 써서 그런다고 했는데 방법을 좀 더 생각해 볼게요.
- closes #211
=> 미션 검색 페이지 리팩토링

one-day-hero/src/components/domain/survey/MandatorySurvey.tsx, one-day-hero/src/components/domain/survey/OptionalSurvey.tsx, one-day-hero/src/types/schema.ts
이미지 미 첨부 시 설정한 에러메세지가 나오지 않았던 버그 수정했습니다. 
> 일단 react-hook-form 에서 제공해 주는 메서드를 사용해서 해결했는데 왜 스키마에 이미지 에러메세지를 설정했는데 출력이 안되는지 모르겠네요. 조건을 잘 못 단 거 같기도 하고...
> 일단은 스키마 안되는 부분은 뺐고 나중에 리팩토링 해보겠습니다. 
https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/ea03ead6-2a50-4f4a-8a9e-895bb40eed44
- closes #214
=> 이미지 에러 메세지 버그 수정

one-day-hero/src/components/common/UploadImage.tsx, one-day-hero/src/components/domain/review/ReviewForm.tsx, one-day-hero/src/services/review.ts, one-day-hero/src/types/response.ts
- 리뷰 수정 중에 기존 이미지를 가져오고 삭제하는 기능을 구현했습니다.
- UploadImage 컴포넌트에 해당 부분을 구현했고 이전 방식으로도 동작하도록 구현했습니다.
- 이미지 개수 제한도 기존 이미지 개수를 합쳐서 계산합니다.
- closes #233
=> 리뷰 수정 중 이미지 삭제 api 연결

one-day-hero/src/app/notification/page.tsx, one-day-hero/src/components/common/DayList.tsx, one-day-hero/src/components/common/Select.tsx, one-day-hero/src/components/common/ToggleButton.tsx, one-day-hero/src/components/domain/survey/MandatorySurvey.tsx, one-day-hero/src/components/domain/survey/OptionalSurvey.tsx, one-day-hero/src/types/response.ts
필수 조사 페이지 사진을 제외하고 기존 프로필의 닉네임과 자기소개를 불러 올 수 있도록 수정했습니다.  
> mandatory survey 부분만 봐주시면 됩니다. 
https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/65764be2-115e-4a80-92fb-f37432c2967f
프로필 페이지 이미지가 기본 이미지로 고정 되어 있는 듯 합니다. 
- closes #237
=> 필수 조사 페이지 닉네임, 자기소개 프로필 기본 값 처리

one-day-hero/src/app/api/createMandatorySurvey/route.ts, one-day-hero/src/app/api/createOptionalSurvey/route.ts, one-day-hero/src/app/api/createPost/route.ts, one-day-hero/src/app/api/createReview/route.ts, one-day-hero/src/app/api/editReview/[slug]/route.ts, one-day-hero/src/app/api/revalidateTag/route.ts, one-day-hero/src/app/api/token/route.ts, one-day-hero/src/app/chatting/[slug]/layout.tsx, one-day-hero/src/app/chatting/[slug]/page.tsx, one-day-hero/src/app/citizenProfile/[slug]/page.tsx, one-day-hero/src/app/heroProfile/[slug]/page.tsx, one-day-hero/src/app/profile/page.tsx, one-day-hero/src/app/search/mission/page.tsx, one-day-hero/src/components/common/KebabMenu/KebabModal.tsx, one-day-hero/src/components/common/Tabs.tsx, one-day-hero/src/components/domain/chatting/MissionProgressButtonBar.tsx, one-day-hero/src/components/domain/mission/create/CreateForm.tsx, one-day-hero/src/components/domain/review/ReviewForm.tsx, one-day-hero/src/components/domain/survey/MandatorySurvey.tsx, one-day-hero/src/components/domain/survey/OptionalSurvey.tsx, one-day-hero/src/services/base.ts, one-day-hero/src/services/map.ts, one-day-hero/src/services/missions.ts, one-day-hero/src/services/notification.ts, one-day-hero/src/services/review.ts, one-day-hero/src/services/search.ts, one-day-hero/src/services/users.ts, one-day-hero/src/types/index.ts
- 캐시를 전체적으로 정리합니다
- 다른 사람의 액션으로 변경되는건 모두 revalidation: 0 으로 캐시를 껐습니다.
- 본인의 액션으로 수정되는 건 tag를 그대로 뒀습니다.
- 클라에서 포스트 요청 보내는 건 revalidateTag 를 쓰기 힘들어서 route 를 하나 만들어서 서버에 전달합니다.
- 폼 제출 후 push 대신 replace 를 사용합니다.
- 프로필 작성은 제외
- Tabs 의 동작도 push 였는데 replace로 바꿨습니다.
- 왔다갔다할 때 이게 더 자연스러울 것 같다고 하더라고요
- form 제출용 route 에서 에러 코드를 body로 전달할 수 있게 했습니다.
- 상태 코드는 0으로만 오길래 400으로 고정했고 받은 에러메세지를 일단 toast로 띄우게 했습니다.
- closes #240
=> 캐시 처리 및 핫 픽스 2

one-day-hero/src/components/domain/mission/create/PostCode.tsx
미션 생성시 금액을 입력하지 않았을 시에 "Expected number, received NaN" 에러가 설정한 에러 대신 뜨는 문제 해결했습니다.  MissionFormSchema 의 price 코드를 아래의 코드로 대체했습니다. 
```
price: z
.number({ invalid_type_error: "포상금을 입력해 주세요!" })
.positive("etc.")
.min(1000, "포상금을 1000원 이상의 값으로 입력해주세요!")
```
> region을 resion으로 실수로 쓰고 계시는 부분이 있길래 한꺼번에 수정했습니다. 
https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/e774d812-2c9e-432a-b896-3dd3ec87d7bd
또 실수로 디벨롭에 바로 수정해 버렸네요... 미안합니다...  변경된 파일이 이 브렌치에 없고 디벨롭으로 바로 올라갔을 거예요.. 
- closes #266
=> 미션 생성시 잘못된 금액 에러 메세지 출력되는 이슈 해결

one-day-hero/src/components/common/FooterButton.tsx, one-day-hero/src/components/common/Info/MissionListItem.tsx, one-day-hero/src/components/common/MissionProgressContainer.tsx, one-day-hero/src/components/domain/chatting/ChattingInputFooter.tsx, one-day-hero/src/components/domain/mission/suggested/SuggestedMissionItem.tsx
- 채팅창 input keydown 이벤트에 isComposing 처리를 추가했습니다.
- 테스트 하다가 일부 어색한 스타일도 수정했습니다
- 아마 맥에서만 발생하는 이슈 같은데 수정되었는지 확인이 필요합니다.
- closes #268
=> 채팅창 엔터 isComposing 처리 추가

one-day-hero/src/app/search/hero/page.tsx, one-day-hero/src/components/domain/search/HeroSearch.tsx, one-day-hero/src/hooks/useDebounce.ts
- 히어로 검색 페이지에서 debouncing 이 사용되는 부분을 useDebounce  hook 으로 따로 분리하고 적용했습니다. 
- 오류 해결
- 검색 페이지에 처음 접속시 (검색을 하지도 않은 상황) 혹은 입력값이 빈 스트링인 상황에서도 `해당 히어로가 존재하지 않습니다.` 라고 텍스트가 뜨는 문제가 있었습니다. 
- null 값과 관련된 로직을 수정해서 해결했습니다. 
- 검색 결과 item 부분 디자인 수정 
https://github.com/prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE/assets/99384699/a86a6a81-1346-4e1c-877c-43addb1791b1
- closes #291
=> useDebounce hook 생성 및 오류 해결
